title: Ethics of Museums - Web Design Final
description: This is my final landing page project for Web Design. 
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
